### ISSUE TITLE
Simple Approach

### ISSUE THREAD

**Issue by RandomAltThing** [peacestorm/ModPE-scripts#4]
You could have just used

<pre>
function useItem(x, y, z, blockId, itemId, side){
if(itemId == paint brush I'd){
Block.setColor(blockId, htmlColor);
}
}

**Comment by RandomAltThing** [comment]
Where <code>paintbrush id</code> is the I'd of the paintbrush and <code>htmlColor</code> is the paintbrush color.

**Comment by peacestorm** [comment]
No, as this would redefine all the already painted blocks, that's why I don't do it like that.

**Comment by peacestorm** [comment]
And I already use the setColor, so there's no need for this page anymore.
