### ISSUE TITLE
.

### ISSUE THREAD

**Issue by RandomAltThing** [peacestorm/ModPE-scripts#5]
<b>This isint the best place to ask, but I'm not sure if you have twitter so I can't ask there</b>

Can you please help at StickyPiston?

https://github.com/StickyPiston/StickyPiston

I have done the (manual) initial commit(s) but I am going to need help with the MCPE Protocal etc, and any other Java stuff would be nice so I don't have to do it all myself.

**Comment by RandomAltThing** [comment]
<code>Thanks ^^</code>

**Comment by peacestorm** [comment]
Please don't open a new issue for something not related to any of of my ModPE-Scripts. My Twitter username is @AgameR_Modder.
